apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-app
  labels:
    app: java-app
spec:
  replicas: 2 # Running two pods for high availability
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-container
        # Pulling from DockerHub (as per Q4 requirement)
        image: sairaskar/a6-q2-java-docker-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort # Allows you to access the app via Minikube IP
